### ISSUE TITLE
Faire une to-do list

### ISSUE THREAD

**Issue by eukavlin** [eukavlin/movie-data#1]
Faire la liste de tous les éléments dont on aura besoin (API, librairies, etc). Se concerter et ouvrir une issue pour chaque tâche.

**Comment by RyderBlack** [comment]
Il faudrait que la To-do list soit faite avant lundi !
 @eukavlin on l'a fait comment/où cette liste ?

**Comment by eukavlin** [comment]
@ryderblack Chaque nouvel élément de la to-do list se traduira par l'ouverture d'une issue dans le répo. Et chacun trouvera une tâche et sera assigné à l'issue en question.
