### ISSUE TITLE
régler beugs mineurs

### ISSUE THREAD

**Issue by RyderBlack** [eukavlin/movie-data#16]
Par exemple, le beug d'affichage lors de la recherche d'un film.

**Comment by khousayoub** [comment]
C'est réglé -- changement de la structure du push dans le tableau qui contient les images dans le fichier js (angular)et enlèvement de la div qui contient la page dans le fichier html du coup on a une seul div qui contient toutes les images et ça régle le problème du vide dans la recherche (y)

**Comment by valdiss** [comment]
Momo plus rapide que son ombre, j'allais vous le proposer justement ^^
