### ISSUE TITLE
Gerer apparition de la div info

### ISSUE THREAD

**Issue by RyderBlack** [eukavlin/movie-data#17]
tag : ng-click, ng-show/ ng-hide, display :none etc...

**Comment by khousayoub** [comment]
Je pense qu'il faut coller la searchbar avec la div d'info comme ça qu'on on scroll en bas on peut faire de la recherche sans remonter

**Comment by eukavlin** [comment]
Ou faire en sorte à ce que la barre de recherche apparaisse toujours, en position fixed en haut de la page, comme ça, on peut la voir tout le temps, je pense que c'est mieux que de la coller à la div d'info.
