### ISSUE TITLE
Lister les infos dont on a besoin

### ISSUE THREAD

**Issue by eukavlin** [eukavlin/movie-data#3]
Faire une liste simple :
> Titre
> Année
> Synopsis
> ...

**Comment by valdiss** [comment]
Infos affichés en preview:
- Affiche
- Titre du flim
- Note (rotten tomato API?)
- Synopsis (en overflow hidden?)
- Nom du réal.

Infos supplémentaires détail:
- TRAILER
- Noms des acteurs
- photos des acteurs
- Titre original
- date de parution
- durée du film
